# Alumno: Gerardo de Miguel González

1.- Crea una función a la que se le pase como input: la media en el eje x, la media en el eje y, la varianza en el eje x, la varianza en el eje y y la covarianza de x e y, junto con un número de puntos N, y devuelva una matriz con N filas y 2 columnas con los números que salen de la distribución gaussiana de dos dimensiones definidas por los valores de input (usar la función MASS::mvrnorm)

In [1]:
library('MASS')

In [2]:
#::GMG::Defino la función con las medias separadas pero las varianzas
#       agrupadas en la matriz de covarianzas en la que las varianzas
#       de X e Y están en la diagonal y las covarianzas en la diagonal
#       inversa de la matriz 2x2 cov_xy
gauss_2d <- function (mu_x, mu_y, cov_xy, n) {
    mu_2d <- c(mu_x, mu_y)
    return(mvrnorm(n = n, mu = mu_2d, Sigma = cov_xy))
}

2.- Genera una matrix x1 usando la función anterior y tomando: N = 1000, mu_x = 2, mu_y = 4, var_x = var_y = 1, y Cov(x,y) = 0.3. Crea una matriz “y1” con tantas filas como la matriz x y asígnale el valor 0. 

In [3]:
#::GMG::Usamos la función anterior
set.seed(1)
X_1 <- gauss_2d(mu_x = 2, 
                mu_y = 4, 
                cov_xy = matrix(data = c(1,0.3,0.3,1), ncol = 2),
                n = 1000)
str(X_1)
head(X_1)

 num [1:1000, 1:2] 3.02 2.11 4.61 2.57 2.76 ...
 - attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : NULL


[,1]     [,2]    
[1,] 3.017236 4.346613
[2,] 2.110941 3.427505
[3,] 4.610817 4.473513
[4,] 2.567596 4.142401
[5,] 2.756902 3.403686
[6,] 2.326005 5.751162

In [4]:
Y_1 <- matrix(data = c(rep(0, nrow(X_1))))
str(Y_1)
head(Y_1)

 num [1:1000, 1] 0 0 0 0 0 0 0 0 0 0 ...


[,1]
[1,] 0   
[2,] 0   
[3,] 0   
[4,] 0   
[5,] 0   
[6,] 0

3.- Repite 2) para otra muestra con N = 1000, mu_x = 6, mu_y = 3, var_x = var_y = 1, y Cov(x,y) = 0.3. Crea una matriz “y2” con tantas filas como la matriz x2 y asígnale el valor 1.

In [5]:
#::GMG::De nuevo usamos la función del primer punto
set.seed(1)
X_2 <- gauss_2d(mu_x = 6, 
                mu_y = 3, 
                cov_xy = matrix(data = c(1,0.3,0.3,1), ncol = 2),
                n = 1000)
str(X_2)
head(X_2)

 num [1:1000, 1:2] 5.62 4.65 4.62 4.81 6.37 ...
 - attr(*, "dimnames")=List of 2
  ..$ : NULL
  ..$ : NULL


[,1]     [,2]    
[1,] 5.622682 1.984234
[2,] 4.654617 2.598757
[3,] 4.618011 3.168478
[4,] 4.812524 4.736733
[5,] 6.374375 2.114127
[6,] 6.045110 2.912772

In [6]:
Y_2 <- matrix(data = c(rep(1, nrow(X_2))))
str(Y_2)
head(Y_2)

 num [1:1000, 1] 1 1 1 1 1 1 1 1 1 1 ...


[,1]
[1,] 1   
[2,] 1   
[3,] 1   
[4,] 1   
[5,] 1   
[6,] 1

4.-Junta las matrices x1, x2, y y1, y2 en una sola matriz x y una sola matriz y.

In [7]:
X <- cbind(X_1, Y_1)
str(X)
head(X)

 num [1:1000, 1:3] 3.02 2.11 4.61 2.57 2.76 ...


[,1]     [,2]     [,3]
[1,] 3.017236 4.346613 0   
[2,] 2.110941 3.427505 0   
[3,] 4.610817 4.473513 0   
[4,] 2.567596 4.142401 0   
[5,] 2.756902 3.403686 0   
[6,] 2.326005 5.751162 0

In [8]:
Y <- cbind(X_2, Y_2)
str(Y)
head(Y)

 num [1:1000, 1:3] 5.62 4.65 4.62 4.81 6.37 ...


[,1]     [,2]     [,3]
[1,] 5.622682 1.984234 1   
[2,] 4.654617 2.598757 1   
[3,] 4.618011 3.168478 1   
[4,] 4.812524 4.736733 1   
[5,] 6.374375 2.114127 1   
[6,] 6.045110 2.912772 1

5.- Usando las funciones de coste y gradiente del ejercicio 4, utiliza optim para un modelo en el que z = alpha_0 + alpha_1 x1 + alpha_2 x2, tomando como vector de parámetros inicial el (0, 0, 0). Calcula y pinta la frontera entre ambas distribuciones. 

6.- Repite otra vez 1, 2, 3 y 4 para obtener otras matrices x e y independientes. Utilizando la “sigma” calculada anteriormente calcula el TPR, TNR, FPR y FNR para valores del threshold = 0.3, 0.5, 0.7.  